name: CI - Compile

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Dependencies
      run:  |
        sudo apt-get update
        sudo apt-get install git build-essential libusb-1.0-0-dev cmake

    - name: Compile
      run: mkdir -p build && cd build && cmake .. && make -j8